version: '3.8'
services:
  ttt:
    build: .
    container_name: ttt-matchmaking
    restart: unless-stopped
    env_file: backend/.env
    ports:
      - "80:80"
    environment:
      - PORT=80
      - adminPW=admin